# Generated by Django 4.1.4 on 2022-12-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='last_name',
        ),
        migrations.AddField(
            model_name='people',
            name='politics',
            field=models.CharField(choices=[('PL', 'Pro-Life'), ('PC', 'Pro-Choice'), ('N', 'Null')], default='N', max_length=2),
        ),
    ]
