# Generated by Django 4.1.4 on 2023-01-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_people_last_name_people_politics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='politics',
            field=models.CharField(choices=[('PL', 'Pro-Life'), ('PC', 'Pro-Choice')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='people',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
