# Generated by Django 4.1.4 on 2023-01-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_people_politics_alter_people_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='politics',
            field=models.BooleanField(),
        ),
    ]
