# Generated by Django 4.1.4 on 2023-01-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_people_politics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='politics',
            field=models.CharField(max_length=2),
        ),
    ]
