# Generated by Django 4.1.4 on 2023-01-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_chatentry_username_chatentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatentry',
            name='user',
        ),
        migrations.AddField(
            model_name='chatentry',
            name='username',
            field=models.CharField(default='nothing', max_length=30),
        ),
    ]
