# Generated by Django 4.1.4 on 2023-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_chatentry_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatentry',
            name='username',
            field=models.CharField(default='no_name', max_length=30),
        ),
    ]
