# Generated by Django 4.1.4 on 2023-01-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_people_topic_alter_chatentry_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('topic', models.CharField(default='', max_length=30)),
                ('user_number', models.IntegerField(default=0)),
                ('user_politics', models.IntegerField(default=0)),
            ],
        ),
    ]
