# Generated by Django 4.1.4 on 2023-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chatrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooms',
            name='user_number',
            field=models.IntegerField(default=1),
        ),
    ]
