# Generated by Django 4.1.4 on 2023-01-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_chatrooms_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
