# Generated by Django 4.1.4 on 2023-01-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_chatrooms_chat_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrooms',
            name='chat_log',
        ),
    ]
