# Generated by Django 4.1.4 on 2023-01-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_chatrooms_chat_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatentry',
            name='timestamp',
            field=models.FloatField(default=0),
        ),
    ]
