# Generated by Django 4.1.4 on 2023-01-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_chatentry_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatentry',
            name='timestamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
