# Generated by Django 4.1.4 on 2023-01-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_chatentry_username_chatentry_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatentry',
            name='timestamp',
            field=models.IntegerField(default=''),
        ),
    ]
