# Generated by Django 4.1.4 on 2023-01-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_chatentry_user1_remove_chatentry_user2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatentry',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatrooms'),
        ),
    ]
