# Generated by Django 4.1.4 on 2023-01-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_chatentry_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='reports',
            new_name='discrimination_reports',
        ),
        migrations.AddField(
            model_name='people',
            name='hostility_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='people',
            name='swearing_reports',
            field=models.IntegerField(default=0),
        ),
    ]
