# Generated by Django 4.1.4 on 2023-01-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_reports_people_discrimination_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
